CREATE TABLE PRODUTO(
	ID_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME_PRODUTO VARCHAR(30) NOT NULL	
);


CREATE TABLE COMPRA(
	ID_COMPRA INT PRIMARY KEY AUTO_INCREMENT,
	DATA_COMPRA DATETIME DEFAULT NOW(),
    TOTAL_PRECO FLOAT
);


CREATE TABLE COMPRA_PRODUTO(
    ID INT NOT NULL AUTO_INCREMENT,
	FK_PRODUTO INT NOT NULL,
	FK_COMPRA INT NOT NULL,
    QTD_PRODUTO INT NOT NULL,
	PRIMARY KEY (ID, FK_PRODUTO, FK_COMPRA),
	FOREIGN KEY(FK_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO),
	FOREIGN KEY(FK_COMPRA) REFERENCES COMPRA(ID_COMPRA)
);



INSERT INTO PRODUTO (NOME_PRODUTO) VALUES ('TECLADO x13'), ('MONITOR 39');

INSERT INTO COMPRA (TOTAL_PRECO) VALUES (0);